//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Frontend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ERRORS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ERRORS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservation.Frontend.Resources.ERRORS", typeof(ERRORS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak możliwości dokonania rezerwacji w dzień wolny.
        /// </summary>
        public static string DayCannotBeOff {
            get {
                return ResourceManager.GetString("DayCannotBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak możliwości dokonania rezerwacji dla nieznanej lokalizacji.
        /// </summary>
        public static string LocationDoesNotExist {
            get {
                return ResourceManager.GetString("LocationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak możliwości dokonania rezerwacji poza wyznaczonymi godzinami.
        /// </summary>
        public static string ReservationCanBeDoneFromNineToNineteen {
            get {
                return ResourceManager.GetString("ReservationCanBeDoneFromNineToNineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak możliwości dokonania rezrwacji w wybranej godzinie.
        /// </summary>
        public static string ReservationCanDoneBasedOnRules {
            get {
                return ResourceManager.GetString("ReservationCanDoneBasedOnRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerwacja z depozytem można dokonać z 2 dniowym wyprzedzeniem.
        /// </summary>
        public static string ReservationWithDepositCanBeDoneInTwoDaysAheadForWebsiteChannel {
            get {
                return ResourceManager.GetString("ReservationWithDepositCanBeDoneInTwoDaysAheadForWebsiteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups wystąpił błąd w aplikacji.
        /// </summary>
        public static string UnknownErrorCode {
            get {
                return ResourceManager.GetString("UnknownErrorCode", resourceCulture);
            }
        }
    }
}
